name: Build & Upload

on:
  push:
    tags:
      - 'build/v*'

jobs:
  build-and-upload:
    name: Build & Upload App
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build .app for simulator
        run: |
          xcodebuild build \
            -project MusicPlayer.xcodeproj \
            -scheme MusicPlayer \
            -destination "platform=iOS Simulator,name=iPhone 16" \
            -derivedDataPath Build

      - name: Archive .app
        run: |
          cd Build/Build/Products/Debug-iphonesimulator
          zip -r MusicPlayer.app.zip MusicPlayer.app

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: MusicPlayer-Simulator
          path: Build/Build/Products/Debug-iphonesimulator/MusicPlayer.app.zip