name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Run unit tests
        run: |
          xcodebuild test \
            -project MusicPlayer.xcodeproj \
            -scheme MusicPlayer \
            -destination "platform=iOS Simulator,name=iPhone 16"